### ISSUE TITLE
hosts_config.py not working with zabbix 4.4.4

### ISSUE THREAD

**Issue by sfl3005** [fmartinlef/zbxtool#1]
Hello Francois,

hosts_config.py running fine with ZBX 4.0 but not functionning with ZBX4.4. 
I have got the following error messageat the first host export :

``` 2020-02-03 16:18:03,745 - INFO - hosts_config.py - zbx_host_config() - host (1/1335) : 08432e50-1600-996d-03c1-8be09cb1bd8d
Traceback (most recent call last):
  File "hosts_config.py", line 469, in <module>
    hosts_tbl = zbx_host_config(zapi, hosts)
  File "hosts_config.py", line 157, in zbx_host_config
    fmt_host = zbx_fmt_host(zapi, host, convert, proxy_name)
  File "hosts_config.py", line 81, in zbx_fmt_host
    tmp_result[key1]["os_full"] = tmp_result[key1]["os_full"].replace(tmp_result
[key1]["name"], "")
TypeError: list indices must be integers or slices, not str
```
issue seems related to proxy field in api response.

Template export is working fine even in 4.4

**Comment by fmartinlef** [comment]
Can you try again with the modified host_config.py file ?
It should work, but I need further investigation.
